config/routes.rb
Rails.application.routes.draw do

# get 'transactions/index'

  devise_for :users
  resources :items do
  member do
    resource :charge
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get '/mypurchase', to: 'transactions#index', as: 'mypurchase'

root to: "items#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/image_uploader.rb
class ImageUploader < Shrine
  # plugins and uploading logic

plugin :remove_attachment
end

app/models/item.rb
class Item < ApplicationRecord
  include ImageUploader[:image]
  # belongs_to  :user
  has_many :charges
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
  has_many :charges
  has_many :transactions

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_item
  def new
  end

  def create

  # Amount in cents
  @item = Item.find(params[:id])
  @amount = (@item.price.to_i) *100



#checking if the current user has a stripe id and if not creating one in our own dtabase

  # if current_user.stripeid.present?
  #   customer = Stripe::Customer.id
  # else
   customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )
   current_user.stripeid = customer.id
   current_user.save()

   charge = Stripe::Charge.create(
     :amount => @amount, # $15.00 this time
     :currency => 'aud',
     :customer => customer.id,
)

    @transaction = Transaction.create(user_id: current_user.id, item_id: @item.id, price: @amount, stripe_transaction_id: charge.id)
    @transaction.save

    # charge = Stripe::Charge.retrieve(
    # :charge => charge.id,
    # :amount => @amount,
    # :currency => 'aud'
    # )



    # charge = Stripe::Charge.create(
    # :amount => 1500, # $15.00 this time
    # :currency => "aud",
    # :customer => stripeid, # Previously stored, then retrieved

  #
  # )

  redirect_to root_path

#we're backing up that stripe charges on our local database

  # @charge = Charge.new(price: @amount)
  # @charge.user = current_user
  # @charge.stripe_token = charge.id

  # if @charge.save
  #   redirect_to charge_path(@charge)
  # else
  #   redirect_to item_path(@item)
  # end

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end




  private
  def set_item
    @item = Item.find(params[:id])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:charge, :show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show

  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end


#stripe does it stuff and creates a charge
  # def charge
  #   price = @item.price
  #   stripe_id = current_user.stripeid
  # end


   #local charge = Charge.new


  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.user_id = current_user

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:price, :category, :image)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = Transaction.where(user_id: current_user.id)
    @items =  Item.where(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/charges/show.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :item_price %>
  </div>

  <!-- <div class="field">
    <%#= form.label :user_id %>
    <%= form.number_field :user_id, id: :item_user_id %>
  </div> -->

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :item_category %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :item_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'partials/userlogin' %>
<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <!-- <th>User</th> -->
      <th>Category</th>
      <th>Image data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.price %></td>
        <!-- <td><%#= item.user_id %></td> -->
        <td><%= item.category %></td>
        <td><img src="<%= item.image_url %>"></td>
        <td><%= link_to 'Show', item %></td>
        <%if item.user_id == current_user.id%>
          <td><%= link_to 'Edit', edit_item_path(item) %></td>
          <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'My Purchase', mypurchase_path %>
<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<!-- <p>
  <strong>User:</strong>
  <%#= @item.user_id %>
</p> -->

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Image data:</strong>
  <img src="<%= @item.image_url %>">
</p>

<%= form_tag charge_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span><%=@item.price %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= @item.price * 100 %>"
          data-locale="auto"></script>
<% end %>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Candy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_userlogin.html.erb
<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, method: :delete, id: "user-login") %>
<% else %>
  <%= link_to('Login', new_user_session_path)  %>
<% end %>

app/views/photos/_form.html.erb
<%= form_for @photo do |f| %>
  <%= render "shared/errors", object: @photo %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :image %>
  <%= f.file_field :image %>

  <% if @photo.image_data? %>
    Remove attachment: <%= f.check_box :remove_image %>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/photos/_photos.html.erb
<div>
  <% if photo.image_data? %>
    <%= image_tag photo.image_url %>
  <% end %>
  <p><%= photo.title %> | <%= link_to 'Edit', edit_photo_path(photo) %></p>
</div>

app/views/photos/edit.html.erb
<h1>Edit Photo</h1>

<%= render 'form' %>

app/views/photos/index.html.erb
<h1>Photos</h1>

<%= link_to 'Add Photo', new_photo_path %>

<%= render @photos %>

app/views/photos/new.html.erb
<h1>Add photo</h1>

<%= render 'form' %>

app/views/transactions/index.html.erb
<h1>Transactions#index</h1>
<p>Find me in app/views/transactions/index.html.erb</p>
<% @transactions.each do |t| %>
<div class="box">
  <div class="list">
    <% item = Item.find_by_id(t.item_id)%>   <!--<!% item = Item.find_by_id(t.item_id)%>  -->
    <%= item.category %>
    <p><strong>price: </strong> <%= t.price/100.round(2)%></p>
    <p><strong>stripe_transaction_id: </strong> <%= t.stripe_transaction_id%></p>
    <p><strong>Date purchased: </strong> <%= t.created_at.strftime("%A the %dth %B %Y")%> <%= time_tag t.created_at %></p>
  </div>
  <img src="<%=item.image_url%>" alt="">
</div>

  <% end %>

<%=link_to "HOME" ,root_path%>